# Generated by Django 3.0.2 on 2020-03-08 20:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('auctions', '0002_auto_20200308_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
